
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode Keystore and Setup Build
      env:
        SIGNING_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      run: |
        printf "%s" "$SIGNING_KEY_STORE_BASE64" | base64 --decode > app/keystore.jks
        echo "KEYSTORE_FILE=keystore.jks" >> $GITHUB_ENV
        echo "KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}" >> $GITHUB_ENV
        echo "KEY_ALIAS=${KEY_ALIAS}" >> $GITHUB_ENV
        echo "KEY_PASSWORD=${KEYSTORE_PASSWORD}" >> $GITHUB_ENV

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.4'
        arguments: :app:assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kozt-now-playing-apk
        path: app/build/outputs/apk/release/kozt-now-playing-*.apk
